version: '3.5'

services:
  mern_app: # Frontend
    build:
      context: ./docker/app/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - mern_app
    stdin_open: true
    volumes:
      - "./app:/home/app"
  
  mern_backend:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - mern_app
    stdin_open: true
    volumes:
      - "./backend:/home/backend"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    networks:
    - mern_app
    volumes:
      - "./database:/data/db"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    networks:
    - mern_app

networks: 
  mern_app:
    name: mern_app
